plugins {
    id 'java'
    id 'groovy'
    id 'jacoco'
}

group = 'ru.nsu.bondar'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:3.0.25'
    //implementation 'org.eclipse.jgit:org.eclipse.jgit:6.7.0.202309050840-r'
    //implementation 'org.jsoup:jsoup:1.17.2'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}